name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: echo Starting project build!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          mvn compile
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: run test
        run: echo running tests
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        name: deploy to production
        run : echo deploy successful