name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: echo Starting project build!
      - name: Setup up JDK
        uses: actions/setup-java@v3
        with:
            java-version: '20.0.1'
            distribution: 'temurin'
      - name: Compile with maven
        run: |
          echo Add other actions to build,
          mvn compile

  test:

    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v1
      - name: run test
        run: echo running tests

  deploy:

    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v1
      - name: deploy to production
        run : echo deploy successful